# Generated by Django 4.1.1 on 2022-11-06 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=50)),
                ('price', models.IntegerField(max_length=15)),
                ('URL', models.CharField(max_length=200)),
                ('photo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pants_size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waist_size', models.IntegerField()),
                ('hip_size', models.IntegerField()),
                ('thigh_size', models.IntegerField()),
                ('calf_size', models.IntegerField()),
                ('rise', models.IntegerField()),
                ('inseam', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('chest_size', models.IntegerField()),
                ('waist_size', models.IntegerField()),
                ('thigh_size', models.IntegerField()),
                ('calf_size', models.IntegerField()),
                ('purchased', models.ManyToManyField(related_name='user_purchased', to='clothes.clothes')),
                ('scrapped', models.ManyToManyField(related_name='user_scrapped', to='clothes.clothes')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_time', models.TimeField()),
                ('content', models.TextField()),
                ('photo', models.CharField(max_length=200)),
                ('reviewing_clothes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothes_review', to='clothes.clothes')),
                ('uploaded_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_review', to='clothes.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_time', models.TimeField()),
                ('content', models.TextField()),
                ('original_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_uploaded', to='clothes.review')),
                ('uploaded_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_comments', to='clothes.user')),
            ],
        ),
        migrations.AddField(
            model_name='clothes',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clothes.pants_size'),
        ),
    ]
