# Generated by Django 4.1.1 on 2022-11-06 09:12

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Myuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nickname', models.CharField(max_length=50)),
                ('chest_size', models.IntegerField()),
                ('waist_size', models.IntegerField()),
                ('thigh_size', models.IntegerField()),
                ('calf_size', models.IntegerField()),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('URL', models.CharField(max_length=200)),
                ('photo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pants_size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waist_size', models.IntegerField()),
                ('hip_size', models.IntegerField()),
                ('thigh_size', models.IntegerField()),
                ('calf_size', models.IntegerField()),
                ('rise', models.IntegerField()),
                ('inseam', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_time', models.TimeField()),
                ('content', models.TextField()),
                ('photo', models.CharField(max_length=200)),
                ('reviewing_clothes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothes_review', to='clothes.clothes')),
                ('uploaded_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_review', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_time', models.TimeField()),
                ('content', models.TextField()),
                ('original_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_uploaded', to='clothes.review')),
                ('uploaded_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='clothes',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clothes.pants_size'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='purchased',
            field=models.ManyToManyField(related_name='user_purchased', to='clothes.clothes'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='scrapped',
            field=models.ManyToManyField(related_name='user_scrapped', to='clothes.clothes'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
