# Generated by Django 4.1.3 on 2022-12-01 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recommended',
            field=models.ManyToManyField(related_name='user_recommended', to='clothes.clothes'),
        ),
    ]
