# Generated by Django 4.1.3 on 2022-11-15 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_remove_myuser_chest_size_myuser_length_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pants_size',
            old_name='hip_size',
            new_name='length',
        ),
        migrations.RemoveField(
            model_name='pants_size',
            name='inseam',
        ),
        migrations.RemoveField(
            model_name='pants_size',
            name='rise',
        ),
    ]
