# Generated by Django 4.1.3 on 2022-12-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_user_recommended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='recommended',
            field=models.ManyToManyField(related_name='user_recommended', to='clothes.size'),
        ),
    ]
