# Generated by Django 4.1.3 on 2022-12-05 08:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0003_alter_user_recommended'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='recommended_user',
            field=models.ManyToManyField(related_name='recommended_review', to=settings.AUTH_USER_MODEL),
        ),
    ]
