# Generated by Django 4.1.3 on 2022-12-09 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0004_review_recommended_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='original_review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_list', to='clothes.review'),
        ),
    ]
