# Generated by Django 4.1.3 on 2022-12-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0005_alter_comment_original_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='photo',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
